import './globals.css'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const displayFont = localFont({
  src: [
    {
      path: '../../public/fonts/GoogleSansDisplay-Regular-v1.27.ttf',
      weight: '400'
    },
    {
      path: '../../public/fonts/GoogleSansDisplay-Medium-v1.27.ttf',
      weight: '700'
    }
  ],
  variable: '--font-displayFont'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className={`${displayFont.variable} font-sans`}>{children}</body>
    </html>
  )
}
